### ISSUE TITLE
note

### ISSUE THREAD

**Issue by crisdosaygo** [DatanewsOrg/google-news-js#2]
Hey @caballeto thanks for your follow! :) 

Anyway, just noticed you wrote "scrap Google news" while funny I suppose you meant "scrape" in the repository description. :)

**Comment by caballeto** [comment]
Haha, good catch!

**Comment by caballeto** [comment]
Fixed. By the way, you've had great job description ;D

**Comment by crisdosaygo** [comment]
I know right? :) I thought that's why you followed me

**Comment by caballeto** [comment]
@cris691 Right, I like people with no BS talk
